-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.ArticleModelContentField exposing (..)

import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


blocks :
    SelectionSet decodesTo Datocms.Object.ImageContentRecord
    -> SelectionSet (List decodesTo) Datocms.Object.ArticleModelContentField
blocks object____ =
    Object.selectionForCompositeField "blocks" [] object____ (Basics.identity >> Decode.list)


links :
    SelectionSet decodesTo Datocms.Object.ArticleRecord
    -> SelectionSet (List decodesTo) Datocms.Object.ArticleModelContentField
links object____ =
    Object.selectionForCompositeField "links" [] object____ (Basics.identity >> Decode.list)


value : SelectionSet ScalarCodecs.JsonField Datocms.Object.ArticleModelContentField
value =
    Object.selectionForField "ScalarCodecs.JsonField" "value" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecJsonField |> .decoder)
