-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.BannerAttributionRecordListMultiLocaleField exposing (..)

import Datocms.Enum.SiteLocale
import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


locale : SelectionSet (Maybe Datocms.Enum.SiteLocale.SiteLocale) Datocms.Object.BannerAttributionRecordListMultiLocaleField
locale =
    Object.selectionForField "(Maybe Enum.SiteLocale.SiteLocale)" "locale" [] (Datocms.Enum.SiteLocale.decoder |> Decode.nullable)


value :
    SelectionSet decodesTo Datocms.Object.BannerAttributionRecord
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Datocms.Object.BannerAttributionRecordListMultiLocaleField
value object____ =
    Object.selectionForCompositeField "value" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)
