-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.BannerAttributionRecord exposing (..)

import Datocms.Enum.ItemStatus
import Datocms.Enum.SiteLocale
import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


createdAt_ : SelectionSet ScalarCodecs.DateTime Datocms.Object.BannerAttributionRecord
createdAt_ =
    Object.selectionForField "ScalarCodecs.DateTime" "_createdAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


firstPublishedAt_ : SelectionSet (Maybe ScalarCodecs.DateTime) Datocms.Object.BannerAttributionRecord
firstPublishedAt_ =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "_firstPublishedAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


isValid_ : SelectionSet ScalarCodecs.BooleanType Datocms.Object.BannerAttributionRecord
isValid_ =
    Object.selectionForField "ScalarCodecs.BooleanType" "_isValid" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecBooleanType |> .decoder)


modelApiKey_ : SelectionSet String Datocms.Object.BannerAttributionRecord
modelApiKey_ =
    Object.selectionForField "String" "_modelApiKey" [] Decode.string


publicationScheduledAt_ : SelectionSet (Maybe ScalarCodecs.DateTime) Datocms.Object.BannerAttributionRecord
publicationScheduledAt_ =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "_publicationScheduledAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


publishedAt_ : SelectionSet (Maybe ScalarCodecs.DateTime) Datocms.Object.BannerAttributionRecord
publishedAt_ =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "_publishedAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


type alias SeoMetaTagsOptionalArguments =
    { locale : OptionalArgument Datocms.Enum.SiteLocale.SiteLocale }


{-| SEO meta tags

  - locale - The locale to use to fetch the field's content

-}
seoMetaTags_ :
    (SeoMetaTagsOptionalArguments -> SeoMetaTagsOptionalArguments)
    -> SelectionSet decodesTo Datocms.Object.Tag
    -> SelectionSet (List decodesTo) Datocms.Object.BannerAttributionRecord
seoMetaTags_ fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { locale = Absent }

        optionalArgs____ =
            [ Argument.optional "locale" filledInOptionals____.locale (Encode.enum Datocms.Enum.SiteLocale.toString) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "_seoMetaTags" optionalArgs____ object____ (Basics.identity >> Decode.list)


status_ : SelectionSet Datocms.Enum.ItemStatus.ItemStatus Datocms.Object.BannerAttributionRecord
status_ =
    Object.selectionForField "Enum.ItemStatus.ItemStatus" "_status" [] Datocms.Enum.ItemStatus.decoder


unpublishingScheduledAt_ : SelectionSet (Maybe ScalarCodecs.DateTime) Datocms.Object.BannerAttributionRecord
unpublishingScheduledAt_ =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "_unpublishingScheduledAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


updatedAt_ : SelectionSet ScalarCodecs.DateTime Datocms.Object.BannerAttributionRecord
updatedAt_ =
    Object.selectionForField "ScalarCodecs.DateTime" "_updatedAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


author : SelectionSet (Maybe String) Datocms.Object.BannerAttributionRecord
author =
    Object.selectionForField "(Maybe String)" "author" [] (Decode.string |> Decode.nullable)


createdAt : SelectionSet ScalarCodecs.DateTime Datocms.Object.BannerAttributionRecord
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


id : SelectionSet ScalarCodecs.ItemId Datocms.Object.BannerAttributionRecord
id =
    Object.selectionForField "ScalarCodecs.ItemId" "id" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecItemId |> .decoder)


licenseLink : SelectionSet (Maybe String) Datocms.Object.BannerAttributionRecord
licenseLink =
    Object.selectionForField "(Maybe String)" "licenseLink" [] (Decode.string |> Decode.nullable)


licenseName : SelectionSet (Maybe String) Datocms.Object.BannerAttributionRecord
licenseName =
    Object.selectionForField "(Maybe String)" "licenseName" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet ScalarCodecs.DateTime Datocms.Object.BannerAttributionRecord
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
