-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.ColorField exposing (..)

import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


alpha : SelectionSet (Maybe ScalarCodecs.IntType) Datocms.Object.ColorField
alpha =
    Object.selectionForField "(Maybe ScalarCodecs.IntType)" "alpha" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecIntType |> .decoder |> Decode.nullable)


blue : SelectionSet (Maybe ScalarCodecs.IntType) Datocms.Object.ColorField
blue =
    Object.selectionForField "(Maybe ScalarCodecs.IntType)" "blue" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecIntType |> .decoder |> Decode.nullable)


green : SelectionSet (Maybe ScalarCodecs.IntType) Datocms.Object.ColorField
green =
    Object.selectionForField "(Maybe ScalarCodecs.IntType)" "green" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecIntType |> .decoder |> Decode.nullable)


hex : SelectionSet (Maybe String) Datocms.Object.ColorField
hex =
    Object.selectionForField "(Maybe String)" "hex" [] (Decode.string |> Decode.nullable)


red : SelectionSet (Maybe ScalarCodecs.IntType) Datocms.Object.ColorField
red =
    Object.selectionForField "(Maybe ScalarCodecs.IntType)" "red" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecIntType |> .decoder |> Decode.nullable)
