-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.FocalPoint exposing (..)

import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


x : SelectionSet (Maybe ScalarCodecs.FloatType) Datocms.Object.FocalPoint
x =
    Object.selectionForField "(Maybe ScalarCodecs.FloatType)" "x" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecFloatType |> .decoder |> Decode.nullable)


y : SelectionSet (Maybe ScalarCodecs.FloatType) Datocms.Object.FocalPoint
y =
    Object.selectionForField "(Maybe ScalarCodecs.FloatType)" "y" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecFloatType |> .decoder |> Decode.nullable)
