-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.GlobalSeoField exposing (..)

import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


facebookPageUrl : SelectionSet (Maybe String) Datocms.Object.GlobalSeoField
facebookPageUrl =
    Object.selectionForField "(Maybe String)" "facebookPageUrl" [] (Decode.string |> Decode.nullable)


fallbackSeo :
    SelectionSet decodesTo Datocms.Object.SeoField
    -> SelectionSet (Maybe decodesTo) Datocms.Object.GlobalSeoField
fallbackSeo object____ =
    Object.selectionForCompositeField "fallbackSeo" [] object____ (Basics.identity >> Decode.nullable)


siteName : SelectionSet (Maybe String) Datocms.Object.GlobalSeoField
siteName =
    Object.selectionForField "(Maybe String)" "siteName" [] (Decode.string |> Decode.nullable)


titleSuffix : SelectionSet (Maybe String) Datocms.Object.GlobalSeoField
titleSuffix =
    Object.selectionForField "(Maybe String)" "titleSuffix" [] (Decode.string |> Decode.nullable)


twitterAccount : SelectionSet (Maybe String) Datocms.Object.GlobalSeoField
twitterAccount =
    Object.selectionForField "(Maybe String)" "twitterAccount" [] (Decode.string |> Decode.nullable)
