-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.ImageContentRecord exposing (..)

import Datocms.Enum.ItemStatus
import Datocms.Enum.SiteLocale
import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


createdAt_ : SelectionSet ScalarCodecs.DateTime Datocms.Object.ImageContentRecord
createdAt_ =
    Object.selectionForField "ScalarCodecs.DateTime" "_createdAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


firstPublishedAt_ : SelectionSet (Maybe ScalarCodecs.DateTime) Datocms.Object.ImageContentRecord
firstPublishedAt_ =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "_firstPublishedAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


isValid_ : SelectionSet ScalarCodecs.BooleanType Datocms.Object.ImageContentRecord
isValid_ =
    Object.selectionForField "ScalarCodecs.BooleanType" "_isValid" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecBooleanType |> .decoder)


modelApiKey_ : SelectionSet String Datocms.Object.ImageContentRecord
modelApiKey_ =
    Object.selectionForField "String" "_modelApiKey" [] Decode.string


publicationScheduledAt_ : SelectionSet (Maybe ScalarCodecs.DateTime) Datocms.Object.ImageContentRecord
publicationScheduledAt_ =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "_publicationScheduledAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


publishedAt_ : SelectionSet (Maybe ScalarCodecs.DateTime) Datocms.Object.ImageContentRecord
publishedAt_ =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "_publishedAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


type alias SeoMetaTagsOptionalArguments =
    { locale : OptionalArgument Datocms.Enum.SiteLocale.SiteLocale }


{-| SEO meta tags

  - locale - The locale to use to fetch the field's content

-}
seoMetaTags_ :
    (SeoMetaTagsOptionalArguments -> SeoMetaTagsOptionalArguments)
    -> SelectionSet decodesTo Datocms.Object.Tag
    -> SelectionSet (List decodesTo) Datocms.Object.ImageContentRecord
seoMetaTags_ fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { locale = Absent }

        optionalArgs____ =
            [ Argument.optional "locale" filledInOptionals____.locale (Encode.enum Datocms.Enum.SiteLocale.toString) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "_seoMetaTags" optionalArgs____ object____ (Basics.identity >> Decode.list)


status_ : SelectionSet Datocms.Enum.ItemStatus.ItemStatus Datocms.Object.ImageContentRecord
status_ =
    Object.selectionForField "Enum.ItemStatus.ItemStatus" "_status" [] Datocms.Enum.ItemStatus.decoder


unpublishingScheduledAt_ : SelectionSet (Maybe ScalarCodecs.DateTime) Datocms.Object.ImageContentRecord
unpublishingScheduledAt_ =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "_unpublishingScheduledAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


updatedAt_ : SelectionSet ScalarCodecs.DateTime Datocms.Object.ImageContentRecord
updatedAt_ =
    Object.selectionForField "ScalarCodecs.DateTime" "_updatedAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdAt : SelectionSet ScalarCodecs.DateTime Datocms.Object.ImageContentRecord
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


fullWidth : SelectionSet (Maybe ScalarCodecs.BooleanType) Datocms.Object.ImageContentRecord
fullWidth =
    Object.selectionForField "(Maybe ScalarCodecs.BooleanType)" "fullWidth" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecBooleanType |> .decoder |> Decode.nullable)


id : SelectionSet ScalarCodecs.ItemId Datocms.Object.ImageContentRecord
id =
    Object.selectionForField "ScalarCodecs.ItemId" "id" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecItemId |> .decoder)


image :
    SelectionSet decodesTo Datocms.Object.FileField
    -> SelectionSet (Maybe decodesTo) Datocms.Object.ImageContentRecord
image object____ =
    Object.selectionForCompositeField "image" [] object____ (Basics.identity >> Decode.nullable)


updatedAt : SelectionSet ScalarCodecs.DateTime Datocms.Object.ImageContentRecord
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
