-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.SeoField exposing (..)

import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


description : SelectionSet (Maybe String) Datocms.Object.SeoField
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


image :
    SelectionSet decodesTo Datocms.Object.FileField
    -> SelectionSet (Maybe decodesTo) Datocms.Object.SeoField
image object____ =
    Object.selectionForCompositeField "image" [] object____ (Basics.identity >> Decode.nullable)


title : SelectionSet (Maybe String) Datocms.Object.SeoField
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


twitterCard : SelectionSet (Maybe String) Datocms.Object.SeoField
twitterCard =
    Object.selectionForField "(Maybe String)" "twitterCard" [] (Decode.string |> Decode.nullable)
