-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.StringMultiLocaleField exposing (..)

import Datocms.Enum.SiteLocale
import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


locale : SelectionSet (Maybe Datocms.Enum.SiteLocale.SiteLocale) Datocms.Object.StringMultiLocaleField
locale =
    Object.selectionForField "(Maybe Enum.SiteLocale.SiteLocale)" "locale" [] (Datocms.Enum.SiteLocale.decoder |> Decode.nullable)


value : SelectionSet (Maybe String) Datocms.Object.StringMultiLocaleField
value =
    Object.selectionForField "(Maybe String)" "value" [] (Decode.string |> Decode.nullable)
