-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object.Tag exposing (..)

import Datocms.InputObject
import Datocms.Interface
import Datocms.Object
import Datocms.Scalar
import Datocms.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


attributes : SelectionSet (Maybe ScalarCodecs.MetaTagAttributes) Datocms.Object.Tag
attributes =
    Object.selectionForField "(Maybe ScalarCodecs.MetaTagAttributes)" "attributes" [] (ScalarCodecs.codecs |> Datocms.Scalar.unwrapCodecs |> .codecMetaTagAttributes |> .decoder |> Decode.nullable)


content : SelectionSet (Maybe String) Datocms.Object.Tag
content =
    Object.selectionForField "(Maybe String)" "content" [] (Decode.string |> Decode.nullable)


tag : SelectionSet String Datocms.Object.Tag
tag =
    Object.selectionForField "String" "tag" [] Decode.string
