-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Enum.FaviconType exposing (..)

import Json.Decode as Decode exposing (Decoder)


type FaviconType
    = Icon
    | AppleTouchIcon
    | MsApplication


list : List FaviconType
list =
    [ Icon, AppleTouchIcon, MsApplication ]


decoder : Decoder FaviconType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "icon" ->
                        Decode.succeed Icon

                    "appleTouchIcon" ->
                        Decode.succeed AppleTouchIcon

                    "msApplication" ->
                        Decode.succeed MsApplication

                    _ ->
                        Decode.fail ("Invalid FaviconType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : FaviconType -> String
toString enum____ =
    case enum____ of
        Icon ->
            "icon"

        AppleTouchIcon ->
            "appleTouchIcon"

        MsApplication ->
            "msApplication"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe FaviconType
fromString enumString____ =
    case enumString____ of
        "icon" ->
            Just Icon

        "appleTouchIcon" ->
            Just AppleTouchIcon

        "msApplication" ->
            Just MsApplication

        _ ->
            Nothing
