-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Enum.ImgixParamsMarkFit exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ImgixParamsMarkFit
    = Clip
    | Crop
    | Fill
    | Max
    | Scale


list : List ImgixParamsMarkFit
list =
    [ Clip, Crop, Fill, Max, Scale ]


decoder : Decoder ImgixParamsMarkFit
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "clip" ->
                        Decode.succeed Clip

                    "crop" ->
                        Decode.succeed Crop

                    "fill" ->
                        Decode.succeed Fill

                    "max" ->
                        Decode.succeed Max

                    "scale" ->
                        Decode.succeed Scale

                    _ ->
                        Decode.fail ("Invalid ImgixParamsMarkFit type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ImgixParamsMarkFit -> String
toString enum____ =
    case enum____ of
        Clip ->
            "clip"

        Crop ->
            "crop"

        Fill ->
            "fill"

        Max ->
            "max"

        Scale ->
            "scale"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ImgixParamsMarkFit
fromString enumString____ =
    case enumString____ of
        "clip" ->
            Just Clip

        "crop" ->
            Just Crop

        "fill" ->
            Just Fill

        "max" ->
            Just Max

        "scale" ->
            Just Scale

        _ ->
            Nothing
