-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Enum.ImgixParamsTrim exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ImgixParamsTrim
    = Auto
    | Color


list : List ImgixParamsTrim
list =
    [ Auto, Color ]


decoder : Decoder ImgixParamsTrim
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "auto" ->
                        Decode.succeed Auto

                    "color" ->
                        Decode.succeed Color

                    _ ->
                        Decode.fail ("Invalid ImgixParamsTrim type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ImgixParamsTrim -> String
toString enum____ =
    case enum____ of
        Auto ->
            "auto"

        Color ->
            "color"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ImgixParamsTrim
fromString enumString____ =
    case enumString____ of
        "auto" ->
            Just Auto

        "color" ->
            Just Color

        _ ->
            Nothing
