-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Enum.ImgixParamsFill exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ImgixParamsFill
    = Solid
    | Blur


list : List ImgixParamsFill
list =
    [ Solid, Blur ]


decoder : Decoder ImgixParamsFill
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "solid" ->
                        Decode.succeed Solid

                    "blur" ->
                        Decode.succeed Blur

                    _ ->
                        Decode.fail ("Invalid ImgixParamsFill type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ImgixParamsFill -> String
toString enum____ =
    case enum____ of
        Solid ->
            "solid"

        Blur ->
            "blur"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ImgixParamsFill
fromString enumString____ =
    case enumString____ of
        "solid" ->
            Just Solid

        "blur" ->
            Just Blur

        _ ->
            Nothing
