-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Enum.ResolutionType exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ResolutionType
    = Icon
    | Small
    | Medium
    | Large


list : List ResolutionType
list =
    [ Icon, Small, Medium, Large ]


decoder : Decoder ResolutionType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "icon" ->
                        Decode.succeed Icon

                    "small" ->
                        Decode.succeed Small

                    "medium" ->
                        Decode.succeed Medium

                    "large" ->
                        Decode.succeed Large

                    _ ->
                        Decode.fail ("Invalid ResolutionType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ResolutionType -> String
toString enum____ =
    case enum____ of
        Icon ->
            "icon"

        Small ->
            "small"

        Medium ->
            "medium"

        Large ->
            "large"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ResolutionType
fromString enumString____ =
    case enumString____ of
        "icon" ->
            Just Icon

        "small" ->
            Just Small

        "medium" ->
            Just Medium

        "large" ->
            Just Large

        _ ->
            Nothing
