-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Enum.VideoMp4Res exposing (..)

import Json.Decode as Decode exposing (Decoder)


type VideoMp4Res
    = Low
    | Medium
    | High


list : List VideoMp4Res
list =
    [ Low, Medium, High ]


decoder : Decoder VideoMp4Res
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "low" ->
                        Decode.succeed Low

                    "medium" ->
                        Decode.succeed Medium

                    "high" ->
                        Decode.succeed High

                    _ ->
                        Decode.fail ("Invalid VideoMp4Res type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : VideoMp4Res -> String
toString enum____ =
    case enum____ of
        Low ->
            "low"

        Medium ->
            "medium"

        High ->
            "high"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe VideoMp4Res
fromString enumString____ =
    case enumString____ of
        "low" ->
            Just Low

        "medium" ->
            Just Medium

        "high" ->
            Just High

        _ ->
            Nothing
