-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Object exposing (..)


type ArticleModelContentField
    = ArticleModelContentField


type ArticleModelContentFieldMultiLocaleField
    = ArticleModelContentFieldMultiLocaleField


type ArticleRecord
    = ArticleRecord


type BannerAttributionRecord
    = BannerAttributionRecord


type BannerAttributionRecordListMultiLocaleField
    = BannerAttributionRecordListMultiLocaleField


type CollectionMetadata
    = CollectionMetadata


type ColorField
    = ColorField


type FileField
    = FileField


type FocalPoint
    = FocalPoint


type GlobalSeoField
    = GlobalSeoField


type HomePageRecord
    = HomePageRecord


type ImageContentRecord
    = ImageContentRecord


type ResponsiveImage
    = ResponsiveImage


type SeoField
    = SeoField


type Site
    = Site


type StringMultiLocaleField
    = StringMultiLocaleField


type Tag
    = Tag


type UploadVideoField
    = UploadVideoField


type WebsiteConfigurationRecord
    = WebsiteConfigurationRecord
