-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.Scalar exposing (BooleanType(..), Codecs, CustomData(..), DateTime(..), FloatType(..), IntType(..), ItemId(..), JsonField(..), MetaTagAttributes(..), UploadId(..), defaultCodecs, defineCodecs, unwrapCodecs, unwrapEncoder)

import Graphql.Codec exposing (Codec)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode


type BooleanType
    = BooleanType String


type CustomData
    = CustomData String


type DateTime
    = DateTime String


type FloatType
    = FloatType String


type IntType
    = IntType String


type ItemId
    = ItemId String


type JsonField
    = JsonField String


type MetaTagAttributes
    = MetaTagAttributes String


type UploadId
    = UploadId String


defineCodecs :
    { codecBooleanType : Codec valueBooleanType
    , codecCustomData : Codec valueCustomData
    , codecDateTime : Codec valueDateTime
    , codecFloatType : Codec valueFloatType
    , codecIntType : Codec valueIntType
    , codecItemId : Codec valueItemId
    , codecJsonField : Codec valueJsonField
    , codecMetaTagAttributes : Codec valueMetaTagAttributes
    , codecUploadId : Codec valueUploadId
    }
    -> Codecs valueBooleanType valueCustomData valueDateTime valueFloatType valueIntType valueItemId valueJsonField valueMetaTagAttributes valueUploadId
defineCodecs definitions =
    Codecs definitions


unwrapCodecs :
    Codecs valueBooleanType valueCustomData valueDateTime valueFloatType valueIntType valueItemId valueJsonField valueMetaTagAttributes valueUploadId
    ->
        { codecBooleanType : Codec valueBooleanType
        , codecCustomData : Codec valueCustomData
        , codecDateTime : Codec valueDateTime
        , codecFloatType : Codec valueFloatType
        , codecIntType : Codec valueIntType
        , codecItemId : Codec valueItemId
        , codecJsonField : Codec valueJsonField
        , codecMetaTagAttributes : Codec valueMetaTagAttributes
        , codecUploadId : Codec valueUploadId
        }
unwrapCodecs (Codecs unwrappedCodecs) =
    unwrappedCodecs


unwrapEncoder :
    (RawCodecs valueBooleanType valueCustomData valueDateTime valueFloatType valueIntType valueItemId valueJsonField valueMetaTagAttributes valueUploadId -> Codec getterValue)
    -> Codecs valueBooleanType valueCustomData valueDateTime valueFloatType valueIntType valueItemId valueJsonField valueMetaTagAttributes valueUploadId
    -> getterValue
    -> Graphql.Internal.Encode.Value
unwrapEncoder getter (Codecs unwrappedCodecs) =
    (unwrappedCodecs |> getter |> .encoder) >> Graphql.Internal.Encode.fromJson


type Codecs valueBooleanType valueCustomData valueDateTime valueFloatType valueIntType valueItemId valueJsonField valueMetaTagAttributes valueUploadId
    = Codecs (RawCodecs valueBooleanType valueCustomData valueDateTime valueFloatType valueIntType valueItemId valueJsonField valueMetaTagAttributes valueUploadId)


type alias RawCodecs valueBooleanType valueCustomData valueDateTime valueFloatType valueIntType valueItemId valueJsonField valueMetaTagAttributes valueUploadId =
    { codecBooleanType : Codec valueBooleanType
    , codecCustomData : Codec valueCustomData
    , codecDateTime : Codec valueDateTime
    , codecFloatType : Codec valueFloatType
    , codecIntType : Codec valueIntType
    , codecItemId : Codec valueItemId
    , codecJsonField : Codec valueJsonField
    , codecMetaTagAttributes : Codec valueMetaTagAttributes
    , codecUploadId : Codec valueUploadId
    }


defaultCodecs : RawCodecs BooleanType CustomData DateTime FloatType IntType ItemId JsonField MetaTagAttributes UploadId
defaultCodecs =
    { codecBooleanType =
        { encoder = \(BooleanType raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map BooleanType
        }
    , codecCustomData =
        { encoder = \(CustomData raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map CustomData
        }
    , codecDateTime =
        { encoder = \(DateTime raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map DateTime
        }
    , codecFloatType =
        { encoder = \(FloatType raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map FloatType
        }
    , codecIntType =
        { encoder = \(IntType raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map IntType
        }
    , codecItemId =
        { encoder = \(ItemId raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map ItemId
        }
    , codecJsonField =
        { encoder = \(JsonField raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map JsonField
        }
    , codecMetaTagAttributes =
        { encoder = \(MetaTagAttributes raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map MetaTagAttributes
        }
    , codecUploadId =
        { encoder = \(UploadId raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map UploadId
        }
    }
