-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.ScalarCodecs exposing (..)

import Datocms.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias BooleanType =
    Datocms.Scalar.BooleanType


type alias CustomData =
    Datocms.Scalar.CustomData


type alias DateTime =
    Datocms.Scalar.DateTime


type alias FloatType =
    Datocms.Scalar.FloatType


type alias IntType =
    Datocms.Scalar.IntType


type alias ItemId =
    Datocms.Scalar.ItemId


type alias JsonField =
    Datocms.Scalar.JsonField


type alias MetaTagAttributes =
    Datocms.Scalar.MetaTagAttributes


type alias UploadId =
    Datocms.Scalar.UploadId


codecs : Datocms.Scalar.Codecs BooleanType CustomData DateTime FloatType IntType ItemId JsonField MetaTagAttributes UploadId
codecs =
    Datocms.Scalar.defineCodecs
        { codecBooleanType = defaultCodecs.codecBooleanType
        , codecCustomData = defaultCodecs.codecCustomData
        , codecDateTime = defaultCodecs.codecDateTime
        , codecFloatType = defaultCodecs.codecFloatType
        , codecIntType = defaultCodecs.codecIntType
        , codecItemId = defaultCodecs.codecItemId
        , codecJsonField = defaultCodecs.codecJsonField
        , codecMetaTagAttributes = defaultCodecs.codecMetaTagAttributes
        , codecUploadId = defaultCodecs.codecUploadId
        }
