-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Datocms.VerifyScalarCodecs exposing (..)

{-
   This file is intended to be used to ensure that custom scalar decoder
   files are valid. It is compiled using `elm make` by the CLI.
-}

import Datocms.Scalar
import ScalarCodecs


verify : Datocms.Scalar.Codecs ScalarCodecs.BooleanType ScalarCodecs.CustomData ScalarCodecs.DateTime ScalarCodecs.FloatType ScalarCodecs.IntType ScalarCodecs.ItemId ScalarCodecs.JsonField ScalarCodecs.MetaTagAttributes ScalarCodecs.UploadId
verify =
    ScalarCodecs.codecs
