# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ v2 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          DATOCMS_TOKEN=${DATOCMS_TOKEN} YOUTUBE_API_KEY=${YOUTUBE_API_KEY} npm run build
        env:
          DATOCMS_TOKEN: ${{ secrets.DATOCMS_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
