# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '10 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        shell: bash
        env:
          DATOCMS_TOKEN: ${{ secrets.DATOCMS_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          npm install
          export DATOCMS_TOKEN=$DATOCMS_TOKEN
          export YOUTUBE_API_KEY=$YOUTUBE_API_KEY
          npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.1
        with:
          build_dir: ./dist
          # Write the given domain name to the CNAME file
          fqdn: www.grenat.eu
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
